/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import Controller.RouterController;
import Views.AccountView;
import Views.CarInfoView;
import Views.HomeView;
import Views.PurchaseView;
import Views.RentalsView;
import models.VehicleModel;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import models.AppModel;
import models.DealershipDAO;
import models.UserModel;
import models.VehicleDAO;

/**
 *
 * @author twene
 */
public class MainFrame extends javax.swing.JFrame {

    // some variables for components
    private RentalsView rentalPage;

    final RouterController controller;
    public VehicleDAO vehicleDao;
    public DealershipDAO dealershipDao;
    public VehicleModel selectedItem;
    private static AppModel appState;

    /**
     * Creates new form customerView
     */
    public MainFrame(AppModel appState) {
        initComponents();

        CardLayout cardLayout = new CardLayout();
        content.setLayout(cardLayout);
        vehicleDao = new VehicleDAO();
        dealershipDao = new DealershipDAO();

        controller = new RouterController(content, cardLayout);

        accountButton.setText("Login");

        controller.addView(new HomeView(appState, controller), RouterController.HOME);
        controller.addView(new RentalsView(appState, controller, vehicleDao), RouterController.RENT);
        controller.addView(new PurchaseView(appState, controller, vehicleDao), RouterController.PURCHASE);
        controller.addView(new AccountView(appState, controller, dealershipDao), RouterController.ACCOUNT);
        controller.addView(new CarInfoView(appState, controller, dealershipDao), RouterController.INFO);

        controller.goHome();
        // addComponents();
    }

    public void setAppState(AppModel appState) {

        this.appState = appState;
    }

    public void updateLogin() {
        accountButton.setText("Hi " + appState.currentUser.getUsername());
        // header.revalidate();
        // header.repaint();
    }

    private void addComponents() {

        content.setLayout(new BorderLayout());
        content.add(rentalPage);

    }

    // private void addTesting() {
    //
    // for (int i = 0; i < 5; i++) {
    // rentalPage.addItems(new VehicleModel("Land Rover Discovery", "Ultra", 120,
    // new ImageIcon(getClass().getResource("/images/car.png"))));
    // rentalPage.addItems(new VehicleModel("Kia Picanto", "Standard", 85,
    // new ImageIcon(getClass().getResource("/images/kia.jpg"))));
    // rentalPage.addItems(new VehicleModel("Ford Focus", "Premium", 99,
    // new ImageIcon(getClass().getResource("/images/ford.jpg"))));
    // rentalPage.addItems(new VehicleModel("Toyota Corrola", "Budget", 60,
    // new ImageIcon(getClass().getResource("/images/toyota.png"))));
    // }
    //
    // }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        rentalsButton = new javax.swing.JButton();
        purchaseButton = new javax.swing.JButton();
        accountButton = new javax.swing.JButton();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rent a Car");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1440, 1024));
        setSize(new java.awt.Dimension(1440, 1024));

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setPreferredSize(new java.awt.Dimension(1440, 1024));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        header.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 255));
        jLabel1.setText("J&B Dealership");
        jLabel1.setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 10));

        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(homeButton);

        rentalsButton.setText("Rentals");
        rentalsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentalsButtonActionPerformed(evt);
            }
        });
        jPanel1.add(rentalsButton);

        purchaseButton.setText("Purchase");
        purchaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseButtonActionPerformed(evt);
            }
        });
        jPanel1.add(purchaseButton);

        accountButton.setText("Login");
        accountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
                headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 471,
                                        Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(179, 179, 179)
                                .addComponent(accountButton)
                                .addGap(84, 84, 84)));
        headerLayout.setVerticalGroup(
                headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(headerLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                        headerLayout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addContainerGap()))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                headerLayout.createSequentialGroup()
                                                        .addComponent(accountButton)
                                                        .addContainerGap()))));

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        content.setOpaque(false);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
                contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));
        contentLayout.setVerticalGroup(
                contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 974, Short.MAX_VALUE));

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
                BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        BackgroundLayout.setVerticalGroup(
                BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BackgroundLayout.createSequentialGroup()
                                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rentalsButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rentalsButtonActionPerformed
        // TODO add your handling code here:
        controller.goRentals();
    }// GEN-LAST:event_rentalsButtonActionPerformed

    private void accountButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_accountButtonActionPerformed
        // TODO add your handling code here:
        if (appState.getCurrentUser() == null) {
            // send them to the login page
            appState.currentUser = new UserModel(1, "JasonLeonard", "Jason", "Leonard", "Male", "Admin", 1);
        } else {
            this.updateLogin();
            controller.goAccountPage();
        }

    }// GEN-LAST:event_accountButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        controller.goHome();
    }// GEN-LAST:event_homeButtonActionPerformed

    private void purchaseButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_purchaseButtonActionPerformed
        // TODO add your handling code here:
        controller.goPurchases();
    }// GEN-LAST:event_purchaseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame(appState).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton accountButton;
    private javax.swing.JPanel content;
    private javax.swing.JPanel header;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton purchaseButton;
    private javax.swing.JButton rentalsButton;
    // End of variables declaration//GEN-END:variables
}
