/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import models.FilterModel;

/**
 *
 * @author twene
 */
public class FilterBar extends javax.swing.JPanel {

    FilterModel currentFilter;
    Runnable filter;

    /**
     * Creates new form FilterBar
     */
    public FilterBar() {
        initComponents();

    }

    public void attachFilterModel(FilterModel filter) {
        currentFilter = filter;
        initFilter();
    }

    public void attachFilterFunc(Runnable filterFunc) {
        filter = filterFunc;
    }

    //initalise the filter
    public void initFilter() {
        large.setSelected(false);
        small.setSelected(false);
        premium.setSelected(false);
        budget.setSelected(false);
        medium.setSelected(false);
        standard.setSelected(false);
        suv.setSelected(false);
        priceSlider.setMaximum(currentFilter.getMaxPrice());
        priceSlider.setMinimum(currentFilter.getMinPrice());
        priceSlider.setMinorTickSpacing(currentFilter.getStep());
        priceSlider.setValue(currentFilter.getPrice());
        priceLabel.setText("€" + currentFilter.getPrice());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        carTypeFilter = new javax.swing.JPanel();
        small = new javax.swing.JCheckBox();
        medium = new javax.swing.JCheckBox();
        large = new javax.swing.JCheckBox();
        suv = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        capacityFilter = new javax.swing.JPanel();
        budget = new javax.swing.JCheckBox();
        premium = new javax.swing.JCheckBox();
        standard = new javax.swing.JCheckBox();
        Ultra = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        priceFilter = new javax.swing.JPanel();
        priceSlider = new javax.swing.JSlider();
        formReset = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(372, 918));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Filter By");

        small.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        small.setText("Small");
        small.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallActionPerformed(evt);
            }
        });

        medium.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        medium.setText("Meduim");
        medium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumActionPerformed(evt);
            }
        });

        large.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        large.setText("Large");
        large.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largeActionPerformed(evt);
            }
        });

        suv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        suv.setText("SUV");
        suv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout carTypeFilterLayout = new javax.swing.GroupLayout(carTypeFilter);
        carTypeFilter.setLayout(carTypeFilterLayout);
        carTypeFilterLayout.setHorizontalGroup(
            carTypeFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carTypeFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(carTypeFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(small)
                    .addComponent(medium)
                    .addComponent(large)
                    .addComponent(suv))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        carTypeFilterLayout.setVerticalGroup(
            carTypeFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carTypeFilterLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(small)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(medium)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(large)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(suv)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Class");

        budget.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        budget.setText("Budget");
        budget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                budgetActionPerformed(evt);
            }
        });

        premium.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        premium.setText("Premium");
        premium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                premiumActionPerformed(evt);
            }
        });

        standard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        standard.setText("Standard");
        standard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standardActionPerformed(evt);
            }
        });

        Ultra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Ultra.setText("Ultra");
        Ultra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UltraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout capacityFilterLayout = new javax.swing.GroupLayout(capacityFilter);
        capacityFilter.setLayout(capacityFilterLayout);
        capacityFilterLayout.setHorizontalGroup(
            capacityFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(capacityFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(capacityFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(budget)
                    .addComponent(premium)
                    .addComponent(standard)
                    .addComponent(Ultra))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        capacityFilterLayout.setVerticalGroup(
            capacityFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(capacityFilterLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(budget)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(standard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(premium)
                .addGap(12, 12, 12)
                .addComponent(Ultra)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Max Price");

        priceSlider.setMaximum(300);
        priceSlider.setMinimum(50);
        priceSlider.setPaintLabels(true);
        priceSlider.setPaintTicks(true);
        priceSlider.setSnapToTicks(true);
        priceSlider.setValue(0);
        priceSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                priceSliderStateChanged(evt);
            }
        });

        javax.swing.GroupLayout priceFilterLayout = new javax.swing.GroupLayout(priceFilter);
        priceFilter.setLayout(priceFilterLayout);
        priceFilterLayout.setHorizontalGroup(
            priceFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(priceFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(priceSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        priceFilterLayout.setVerticalGroup(
            priceFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(priceFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(priceSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        formReset.setBackground(new java.awt.Color(204, 0, 255));
        formReset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        formReset.setForeground(new java.awt.Color(255, 255, 255));
        formReset.setText("Reset");
        formReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formResetActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Vehicle Size");

        priceLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(formReset)
                            .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(priceFilter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(capacityFilter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(carTypeFilter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(38, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carTypeFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(capacityFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formReset)
                .addGap(307, 307, 307))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void smallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallActionPerformed
        // TODO add your handling code here:

        currentFilter.setCarSize("small");
        filter.run();
    }//GEN-LAST:event_smallActionPerformed

    private void largeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largeActionPerformed
        // TODO add your handling code here:
        currentFilter.setCarSize("large");

        filter.run();
    }//GEN-LAST:event_largeActionPerformed

    private void budgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_budgetActionPerformed
        // TODO add your handling code here:
        currentFilter.setTypes("Budget");
        filter.run();
    }//GEN-LAST:event_budgetActionPerformed

    private void premiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_premiumActionPerformed
        // TODO add your handling code here:
        currentFilter.setTypes("Premium");
        filter.run();
    }//GEN-LAST:event_premiumActionPerformed

    private void standardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standardActionPerformed
        // TODO add your handling code here:
        currentFilter.setTypes("Standard");
        filter.run();
    }//GEN-LAST:event_standardActionPerformed

    private void formResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formResetActionPerformed
        // TODO add your handling code here:
        currentFilter.reset();
        priceSlider.setValue(currentFilter.getPrice());
        priceLabel.setText("€" + currentFilter.getPrice());
        filter.run();
    }//GEN-LAST:event_formResetActionPerformed

    private void suvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suvActionPerformed
        // TODO add your handling code here:
        currentFilter.setCarSize("suv");
        filter.run();
    }//GEN-LAST:event_suvActionPerformed

    private void mediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumActionPerformed
        // TODO add your handling code here:
        currentFilter.setCarSize("medium");
        filter.run();
    }//GEN-LAST:event_mediumActionPerformed

    private void priceSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_priceSliderStateChanged
        // TODO add your handling code here:
        currentFilter.setPrice(priceSlider.getValue());
        priceLabel.setText("€" + currentFilter.getPrice());
        filter.run();
    }//GEN-LAST:event_priceSliderStateChanged

    private void UltraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UltraActionPerformed
        // TODO add your handling code here:
        currentFilter.setTypes("Ultra");
        filter.run();
    }//GEN-LAST:event_UltraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Ultra;
    private javax.swing.JCheckBox budget;
    private javax.swing.JPanel capacityFilter;
    private javax.swing.JPanel carTypeFilter;
    private javax.swing.JButton formReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JCheckBox large;
    private javax.swing.JCheckBox medium;
    private javax.swing.JCheckBox premium;
    private javax.swing.JPanel priceFilter;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JSlider priceSlider;
    private javax.swing.JCheckBox small;
    private javax.swing.JCheckBox standard;
    private javax.swing.JCheckBox suv;
    // End of variables declaration//GEN-END:variables
}
