/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import models.FilterModel;

/**
 *
 * @author twene
 */
// filterBar class
public class FilterBar extends javax.swing.JPanel {

    // instance variables for holding the filter setting and function for running
    // the
    // filtering
    private FilterModel filterSettings;
    private Runnable filter;

    /**
     * Creates new form FilterBar
     */
    public FilterBar() {
        initComponents();

    }

    // setter method for the filter settings
    public void attachfilterSettings(FilterModel filter) {
        filterSettings = filter;
        initFilter();
    }

    // setter method for the filter function
    public void attachFilterFunc(Runnable filterFunc) {
        filter = filterFunc;
    }

    // initalise the filter
    public void initFilter() {

        // set all check fields to empty
        compact.setSelected(false);
        sport.setSelected(false);
        premium.setSelected(false);
        budget.setSelected(false);
        sedan.setSelected(false);
        standard.setSelected(false);
        supercheck.setSelected(false);

        // set the price slider to the default max price from the filter settings
        priceSlider.setMaximum(filterSettings.getMaxPrice());
        priceSlider.setMinimum(filterSettings.getMinPrice());
        priceSlider.setMinorTickSpacing(filterSettings.getStep());
        priceSlider.setValue(filterSettings.getMaxPrice());
        priceLabel.setText("€" + filterSettings.getPrice());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        carTypeFilter = new javax.swing.JPanel();
        sport = new javax.swing.JCheckBox();
        sedan = new javax.swing.JCheckBox();
        compact = new javax.swing.JCheckBox();
        supercheck = new javax.swing.JCheckBox();
        electric = new javax.swing.JCheckBox();
        hyper = new javax.swing.JCheckBox();
        suv = new javax.swing.JCheckBox();
        hybrid = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        capacityFilter = new javax.swing.JPanel();
        budget = new javax.swing.JCheckBox();
        premium = new javax.swing.JCheckBox();
        standard = new javax.swing.JCheckBox();
        Ultra = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        priceFilter = new javax.swing.JPanel();
        priceSlider = new javax.swing.JSlider();
        formReset = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(372, 918));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Filter By");

        sport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sport.setText("Sport");
        sport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportActionPerformed(evt);
            }
        });

        sedan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sedan.setText("Sedan");
        sedan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sedanActionPerformed(evt);
            }
        });

        compact.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        compact.setText("Compact");
        compact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compactActionPerformed(evt);
            }
        });

        supercheck.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        supercheck.setText("Super");
        supercheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supercheckActionPerformed(evt);
            }
        });

        electric.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        electric.setText("Electric");
        electric.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electricActionPerformed(evt);
            }
        });

        hyper.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hyper.setText("Hyper");
        hyper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hyperActionPerformed(evt);
            }
        });

        suv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        suv.setText("SUV");
        suv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suvActionPerformed(evt);
            }
        });

        hybrid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hybrid.setText("Hybrid");
        hybrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hybridActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout carTypeFilterLayout = new javax.swing.GroupLayout(carTypeFilter);
        carTypeFilter.setLayout(carTypeFilterLayout);
        carTypeFilterLayout.setHorizontalGroup(
                carTypeFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(carTypeFilterLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(carTypeFilterLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sport)
                                        .addComponent(sedan)
                                        .addComponent(compact)
                                        .addComponent(supercheck))
                                .addGap(83, 83, 83)
                                .addGroup(carTypeFilterLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(hyper)
                                        .addComponent(electric)
                                        .addComponent(suv)
                                        .addComponent(hybrid))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        carTypeFilterLayout.setVerticalGroup(
                carTypeFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(carTypeFilterLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(sport)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sedan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(compact)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(supercheck)
                                .addContainerGap(16, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                carTypeFilterLayout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(electric)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(suv)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(hyper)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(hybrid)
                                        .addGap(14, 14, 14)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Class");

        budget.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        budget.setText("Budget");
        budget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                budgetActionPerformed(evt);
            }
        });

        premium.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        premium.setText("Premium");
        premium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                premiumActionPerformed(evt);
            }
        });

        standard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        standard.setText("Standard");
        standard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standardActionPerformed(evt);
            }
        });

        Ultra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Ultra.setText("Luxury");
        Ultra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UltraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout capacityFilterLayout = new javax.swing.GroupLayout(capacityFilter);
        capacityFilter.setLayout(capacityFilterLayout);
        capacityFilterLayout.setHorizontalGroup(
                capacityFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(capacityFilterLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(capacityFilterLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(budget)
                                        .addComponent(premium)
                                        .addComponent(standard)
                                        .addComponent(Ultra))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        capacityFilterLayout.setVerticalGroup(
                capacityFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(capacityFilterLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(budget)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(standard)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(premium)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Ultra)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Max Price");

        priceSlider.setMaximum(300);
        priceSlider.setMinimum(50);
        priceSlider.setPaintLabels(true);
        priceSlider.setPaintTicks(true);
        priceSlider.setSnapToTicks(true);
        priceSlider.setValue(0);
        priceSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                priceSliderStateChanged(evt);
            }
        });

        javax.swing.GroupLayout priceFilterLayout = new javax.swing.GroupLayout(priceFilter);
        priceFilter.setLayout(priceFilterLayout);
        priceFilterLayout.setHorizontalGroup(
                priceFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(priceFilterLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(priceSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 319,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(21, Short.MAX_VALUE)));
        priceFilterLayout.setVerticalGroup(
                priceFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(priceFilterLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(priceSlider, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        formReset.setBackground(new java.awt.Color(204, 0, 255));
        formReset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        formReset.setForeground(new java.awt.Color(255, 255, 255));
        formReset.setText("Reset");
        formReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formResetActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Vehicle Type");

        priceLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel7)
                                                        .addComponent(formReset)
                                                        .addComponent(priceLabel,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 119,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                false)
                                                        .addComponent(priceFilter,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(capacityFilter,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel5,
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(carTypeFilter,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel1,
                                                                javax.swing.GroupLayout.Alignment.LEADING))
                                                .addContainerGap(19, Short.MAX_VALUE)))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel1)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(carTypeFilter, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(capacityFilter, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(priceFilter, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(formReset)
                                .addContainerGap(249, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    // when any of the checkboxes are clicked run the setter function to add this to
    // the filter settings list of selected options
    private void sportActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_sportActionPerformed
        // TODO add your handling code here:

        filterSettings.setCarType("Sport");
        filter.run();
    }// GEN-LAST:event_sportActionPerformed

    private void compactActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_compactActionPerformed
        // TODO add your handling code here:
        filterSettings.setCarType("Compact");

        filter.run();
    }// GEN-LAST:event_compactActionPerformed

    private void budgetActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_budgetActionPerformed
        // TODO add your handling code here:
        filterSettings.setRarity("Budget");
        filter.run();
    }// GEN-LAST:event_budgetActionPerformed

    private void premiumActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_premiumActionPerformed
        // TODO add your handling code here:
        filterSettings.setRarity("Premium");
        filter.run();
    }// GEN-LAST:event_premiumActionPerformed

    private void standardActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_standardActionPerformed
        // TODO add your handling code here:
        filterSettings.setRarity("Standard");
        filter.run();
    }// GEN-LAST:event_standardActionPerformed

    // reset button
    private void formResetActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_formResetActionPerformed
        // TODO add your handling code here:

        // run the fields in the filter settings
        filterSettings.reset();
        // reset the price of the slider
        priceSlider.setValue(filterSettings.getPrice());
        // and reset the label that goes with the slider
        priceLabel.setText("€" + filterSettings.getPrice());

        // run the filter to update the list
        filter.run();
    }// GEN-LAST:event_formResetActionPerformed

    private void supercheckActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_supercheckActionPerformed
        // TODO add your handling code here:
        filterSettings.setCarType("Super");

        // run the filter to ensuer that the list of vehicles to the user is updated
        filter.run();
    }// GEN-LAST:event_supercheckActionPerformed

    private void sedanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_sedanActionPerformed
        // TODO add your handling code here:
        filterSettings.setCarType("Sedan");
        filter.run();
    }// GEN-LAST:event_sedanActionPerformed

    private void priceSliderStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_priceSliderStateChanged
        // TODO add your handling code here:
        filterSettings.setPrice(priceSlider.getValue());
        priceLabel.setText("€" + filterSettings.getPrice());
        filter.run();
    }// GEN-LAST:event_priceSliderStateChanged

    private void UltraActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_UltraActionPerformed
        // TODO add your handling code here:
        filterSettings.setRarity("Ultra");
        filter.run();
    }// GEN-LAST:event_UltraActionPerformed

    private void electricActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_electricActionPerformed
        // TODO add your handling code here:
        filterSettings.setCarType("Electric");
        filter.run();
    }// GEN-LAST:event_electricActionPerformed

    private void hyperActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_hyperActionPerformed
        // TODO add your handling code here:
        filterSettings.setCarType("Hyper");
        filter.run();
    }// GEN-LAST:event_hyperActionPerformed

    private void suvActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_suvActionPerformed
        // TODO add your handling code here:
        filterSettings.setCarType("SUV");
        filter.run();
    }// GEN-LAST:event_suvActionPerformed

    private void hybridActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_hybridActionPerformed
        // TODO add your handling code here:
        filterSettings.setCarType("Hybrid");
        filter.run();
    }// GEN-LAST:event_hybridActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Ultra;
    private javax.swing.JCheckBox budget;
    private javax.swing.JPanel capacityFilter;
    private javax.swing.JPanel carTypeFilter;
    private javax.swing.JCheckBox compact;
    private javax.swing.JCheckBox electric;
    private javax.swing.JButton formReset;
    private javax.swing.JCheckBox hybrid;
    private javax.swing.JCheckBox hyper;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JCheckBox premium;
    private javax.swing.JPanel priceFilter;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JSlider priceSlider;
    private javax.swing.JCheckBox sedan;
    private javax.swing.JCheckBox sport;
    private javax.swing.JCheckBox standard;
    private javax.swing.JCheckBox supercheck;
    private javax.swing.JCheckBox suv;
    // End of variables declaration//GEN-END:variables
}
