/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import Controller.RouterController;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import models.AppModel;
import models.VehicleModel;

/**
 *
 * @author twene
 */
public class VehicleItem extends javax.swing.JPanel {

    RouterController controller;
    AppModel appState;

    /**
     * Creates new form VheicleItem
     */
    public VehicleItem(AppModel appState, RouterController controller) {
        this.controller = controller;
        this.appState = appState;
        initComponents();
    }

    private VehicleModel data;

    public void fillData(VehicleModel data) {

        this.data = data;

        // adding the items from the model to the object itself
        pictureBox1.setImage(data.getVehicleImage());
        rentalClass.setText(data.getVehicleRarity());
        rentalClass.setForeground(Color.decode(data.getRarityColor()));
        price.setText("€" + data.getVehiclePrice());
        jButton1.setText(data.isForRent() ? "Rent" : "Buy");
        name.setText(String.format("%s %s (%s)", data.getVehicleMake(), data.getVehicleModel(), data.getVehicleYear()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VheicleInfo = new javax.swing.JPanel();
        rentalClass = new javax.swing.JLabel();
        actionContainer = new javax.swing.JPanel();
        price = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        pictureBox1 = new third_party.PictureBox();

        setBackground(new java.awt.Color(255, 255, 255));

        VheicleInfo.setBackground(new java.awt.Color(255, 255, 255));

        rentalClass.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        rentalClass.setText("Standard");

        javax.swing.GroupLayout VheicleInfoLayout = new javax.swing.GroupLayout(VheicleInfo);
        VheicleInfo.setLayout(VheicleInfoLayout);
        VheicleInfoLayout.setHorizontalGroup(
            VheicleInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VheicleInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rentalClass)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        VheicleInfoLayout.setVerticalGroup(
            VheicleInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VheicleInfoLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(rentalClass)
                .addContainerGap())
        );

        actionContainer.setBackground(new java.awt.Color(255, 255, 255));

        price.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        price.setText("€120");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("per day");

        jButton1.setBackground(new java.awt.Color(153, 0, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Rent");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        name.setBackground(new java.awt.Color(51, 51, 51));
        name.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        name.setForeground(new java.awt.Color(102, 102, 102));
        name.setText("Land Rover Discovery");

        javax.swing.GroupLayout actionContainerLayout = new javax.swing.GroupLayout(actionContainer);
        actionContainer.setLayout(actionContainerLayout);
        actionContainerLayout.setHorizontalGroup(
            actionContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionContainerLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(actionContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(actionContainerLayout.createSequentialGroup()
                        .addComponent(name)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(actionContainerLayout.createSequentialGroup()
                        .addGroup(actionContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(price))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );
        actionContainerLayout.setVerticalGroup(
            actionContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name)
                .addGap(18, 18, 18)
                .addGroup(actionContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(actionContainerLayout.createSequentialGroup()
                        .addComponent(price)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VheicleInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(actionContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pictureBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pictureBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(VheicleInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actionContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        appState.setSelectedVehicle(this.data);
        controller.goInfoPage();
    }// GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel VheicleInfo;
    private javax.swing.JPanel actionContainer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel name;
    private third_party.PictureBox pictureBox1;
    private javax.swing.JLabel price;
    private javax.swing.JLabel rentalClass;
    // End of variables declaration//GEN-END:variables
}
