/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Controller.AccountRouterController;
import Controller.RouterController;
import Controller.UpdateInterface;
import java.util.concurrent.TimeUnit;

import javax.swing.JOptionPane;

import models.AppModel;
import models.CurrentRentalModel;
import models.DealershipDAO;
import java.awt.Color;

/**
 *
 * @author twene
 */
public class AccountCurrent extends javax.swing.JPanel implements UpdateInterface {
        public CurrentRentalModel currentRentalData;
        public DealershipDAO dealershipDao;
        public AppModel appState;
        private RouterController controller;

        /**
         * Creates new form AccountCurrent
         */
        public AccountCurrent(AppModel appState, RouterController controller, AccountRouterController nestedRouter,
                        DealershipDAO dealershipDao) {
                this.controller = controller;
                this.dealershipDao = dealershipDao;
                this.appState = appState;
                initComponents();
        }

        // override updatePage interface function and update the page accordingly
        @Override
        public void updatePage() {
                // get the current rental from databse
                currentRentalData = dealershipDao.getCurrentRental(this.appState.getCurrentUser().getUserId());

                // check if there is
                if (currentRentalData == null) {
                        // if not then set certain areas invisible
                        returnContainer.setVisible(false);
                        dayLeftContainer.setVisible(false);
                } else {
                        // other wise calculate the days left
                        long diffInMillies = Math.abs(
                                        currentRentalData.getRentReturnDate().getTime()
                                                        - currentRentalData.getRentStartDate().getTime());
                        long diff = TimeUnit.DAYS.convert(diffInMillies, TimeUnit.MILLISECONDS);
                        pictureContainer.setImage(currentRentalData.getVehicleImage());
                        carName.setText(
                                        String.format("%s - %s", currentRentalData.getVehicleMake(),
                                                        currentRentalData.getVehicleModel()));

                        // set panels to visible
                        returnContainer.setVisible(true);
                        dayLeftContainer.setVisible(true);
                        // add the days left to a label
                        daysLeft.setText("" + diff);

                        // the amount of days is left is 3 or less give a visual aid to the user
                        if (diff >= 3) {
                                daysLeft.setForeground(Color.decode("#ff0000"));
                        }
                }

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                carName = new javax.swing.JLabel();
                pictureContainer = new third_party.PictureBox();
                dayLeftContainer = new javax.swing.JPanel();
                jLabel3 = new javax.swing.JLabel();
                daysLeft = new javax.swing.JLabel();
                jSeparator1 = new javax.swing.JSeparator();
                returnContainer = new javax.swing.JPanel();
                jLabel5 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                jComboBox1 = new javax.swing.JComboBox<>();
                returnButton = new javax.swing.JButton();

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
                jLabel1.setText("Rental Overview");

                carName.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
                carName.setText("You have no cars that are being rented");

                dayLeftContainer.setBackground(new java.awt.Color(255, 255, 255));

                jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
                jLabel3.setText("Days Left");

                daysLeft.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
                daysLeft.setText("0");

                javax.swing.GroupLayout dayLeftContainerLayout = new javax.swing.GroupLayout(dayLeftContainer);
                dayLeftContainer.setLayout(dayLeftContainerLayout);
                dayLeftContainerLayout.setHorizontalGroup(
                                dayLeftContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(dayLeftContainerLayout.createSequentialGroup()
                                                                .addGroup(dayLeftContainerLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(dayLeftContainerLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(70, 70, 70)
                                                                                                .addComponent(daysLeft))
                                                                                .addGroup(dayLeftContainerLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(55, 55, 55)
                                                                                                .addComponent(jLabel3)))
                                                                .addContainerGap(51, Short.MAX_VALUE)));
                dayLeftContainerLayout.setVerticalGroup(
                                dayLeftContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(dayLeftContainerLayout.createSequentialGroup()
                                                                .addGap(29, 29, 29)
                                                                .addComponent(jLabel3)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(daysLeft)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
                jLabel5.setText("Return");

                jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
                jLabel8.setText("Select Location");

                jComboBox1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
                jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(
                                new String[] { "Dublin Airport", "Cork", "SuperValue Carpark", "Dundalk" }));
                jComboBox1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jComboBox1ActionPerformed(evt);
                        }
                });

                returnButton.setBackground(new java.awt.Color(255, 0, 0));
                returnButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
                returnButton.setForeground(new java.awt.Color(255, 255, 255));
                returnButton.setText("Return");
                returnButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                returnButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout returnContainerLayout = new javax.swing.GroupLayout(returnContainer);
                returnContainer.setLayout(returnContainerLayout);
                returnContainerLayout.setHorizontalGroup(
                                returnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(returnContainerLayout.createSequentialGroup()
                                                                .addGap(14, 14, 14)
                                                                .addGroup(returnContainerLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(returnButton)
                                                                                .addComponent(jComboBox1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                177,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel8)
                                                                                .addComponent(jLabel5))
                                                                .addContainerGap(82, Short.MAX_VALUE)));
                returnContainerLayout.setVerticalGroup(
                                returnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(returnContainerLayout.createSequentialGroup()
                                                                .addGap(17, 17, 17)
                                                                .addComponent(jLabel5)
                                                                .addGap(28, 28, 28)
                                                                .addComponent(jLabel8)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jComboBox1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                81, Short.MAX_VALUE)
                                                                .addComponent(returnButton)
                                                                .addGap(21, 21, 21)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(86, 86, 86)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(returnContainer,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addContainerGap(
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addComponent(jSeparator1)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(jLabel1)
                                                                                                                                                .addComponent(carName)
                                                                                                                                                .addComponent(dayLeftContainer,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                91,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addComponent(pictureContainer,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                430,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                .addGap(85, 85, 85)))));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(54, 54, 54)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(jLabel1)
                                                                                                .addGap(47, 47, 47)
                                                                                                .addComponent(carName)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(dayLeftContainer,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE))
                                                                                .addComponent(pictureContainer,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                269,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(70, 70, 70)
                                                                .addComponent(jSeparator1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                10,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(27, 27, 27)
                                                                .addComponent(returnContainer,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(214, Short.MAX_VALUE)));
        }// </editor-fold>//GEN-END:initComponents

        private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_returnButtonActionPerformed
                // TODO add your handling code here:

                // when user clicks the return car ensure that that is what they want ot do
                int reply = JOptionPane.showConfirmDialog(null, "Are you sure you want to return this car",
                                "Return Vehicle", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                        JOptionPane.showMessageDialog(null, "Done");

                        // send them home if they return the car in the end
                        // to ensure the view can be updated properly
                        controller.goHome();
                } else {

                }

        }// GEN-LAST:event_returnButtonActionPerformed

        private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox1ActionPerformed
                // TODO add your handling code here:
                // RentModel returnedVehicle = new RentModel(currentRentalModel.getRentID,
                // currentRentalModel.getRentStartDate, currentRentalModel.getRentReturnDate,
                // currentRentalModel.getRentNoOfDays())
                // dealershipDao.updateRental(returnedVehicle);

        }// GEN-LAST:event_jComboBox1ActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel carName;
        private javax.swing.JPanel dayLeftContainer;
        private javax.swing.JLabel daysLeft;
        private javax.swing.JComboBox<String> jComboBox1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JSeparator jSeparator1;
        private third_party.PictureBox pictureContainer;
        private javax.swing.JButton returnButton;
        private javax.swing.JPanel returnContainer;
        // End of variables declaration//GEN-END:variables
}
