package Views;

import Controller.AccountRouterController;
import Controller.RouterController;
import Controller.UpdateInterface;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import models.AppModel;
import models.DealershipDAO;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author twene
 */
public class AccountHistoryView extends javax.swing.JPanel implements UpdateInterface {

        public DealershipDAO dealershipDao;
        public AppModel appState;

        /**
         * Creates new form AccountHistoryView
         */
        public AccountHistoryView(AppModel appState, RouterController controller, AccountRouterController nestedRouter,
                        DealershipDAO dealershipDao) {

                this.dealershipDao = dealershipDao;
                this.appState = appState;
                initComponents();

        }

        @Override
        public void updatePage() {
                this.populateTable();

        }

        // populate the table with the data that was fetched from the database
        public void populateTable() {
                ArrayList<Object[]> purchaseData = dealershipDao.getPurchases(appState.getCurrentUser().getUserId());
                ArrayList<Object[]> rentalData = dealershipDao.getRentals(appState.getCurrentUser().getUserId());

                DefaultTableModel purchaseTableModel = (DefaultTableModel) purchaseTable.getModel();
                DefaultTableModel rentalTableModel = (DefaultTableModel) rentalTable.getModel();

                for (Object[] row : purchaseData) {
                        purchaseTableModel.addRow(row);
                }

                for (Object[] row : rentalData) {
                        rentalTableModel.addRow(row);
                }
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jTabbedPane1 = new javax.swing.JTabbedPane();
                rentalPanel = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                rentalTable = new javax.swing.JTable();
                purchasePanel = new javax.swing.JPanel();
                jScrollPane2 = new javax.swing.JScrollPane();
                purchaseTable = new javax.swing.JTable();

                setBackground(new java.awt.Color(255, 255, 255));

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
                jLabel1.setText("History");

                jTabbedPane1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

                rentalTable.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null }
                                },
                                new String[] {
                                                "RentalID", "Pickup Date", "Return Date", "Days Rented", "Make",
                                                "Model", "Type"
                                }) {
                        Class[] types = new Class[] {
                                        java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class,
                                        java.lang.Integer.class,
                                        java.lang.String.class, java.lang.String.class, java.lang.String.class
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types[columnIndex];
                        }
                });
                jScrollPane1.setViewportView(rentalTable);

                javax.swing.GroupLayout rentalPanelLayout = new javax.swing.GroupLayout(rentalPanel);
                rentalPanel.setLayout(rentalPanelLayout);
                rentalPanelLayout.setHorizontalGroup(
                                rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1014,
                                                                Short.MAX_VALUE));
                rentalPanelLayout.setVerticalGroup(
                                rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 705,
                                                                Short.MAX_VALUE));

                jTabbedPane1.addTab("Rental ", rentalPanel);

                jScrollPane2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

                purchaseTable.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null }
                                },
                                new String[] {
                                                "Purchase ID", "Make", "Model", "Price"
                                }) {
                        Class[] types = new Class[] {
                                        java.lang.Integer.class, java.lang.String.class, java.lang.String.class,
                                        java.lang.Integer.class
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types[columnIndex];
                        }
                });
                jScrollPane2.setViewportView(purchaseTable);

                javax.swing.GroupLayout purchasePanelLayout = new javax.swing.GroupLayout(purchasePanel);
                purchasePanel.setLayout(purchasePanelLayout);
                purchasePanelLayout.setHorizontalGroup(
                                purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1014,
                                                                Short.MAX_VALUE));
                purchasePanelLayout.setVerticalGroup(
                                purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 705,
                                                                Short.MAX_VALUE));

                jTabbedPane1.addTab("Purchase", purchasePanel);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(39, 39, 39)
                                                                .addComponent(jLabel1)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(40, 40, 40)
                                                                .addComponent(jLabel1)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                91,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jTabbedPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                739,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, 0)));
        }// </editor-fold>//GEN-END:initComponents

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel jLabel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTabbedPane jTabbedPane1;
        private javax.swing.JPanel purchasePanel;
        private javax.swing.JTable purchaseTable;
        private javax.swing.JPanel rentalPanel;
        private javax.swing.JTable rentalTable;
        // End of variables declaration//GEN-END:variables
}
