/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Controller.AccountRouterController;
import Controller.RouterController;
import Controller.UpdateInterface;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import models.AppModel;
import models.DealershipDAO;

/**
 *
 * @author twene
 */
public class AccountView extends javax.swing.JPanel implements UpdateInterface {

        private AccountRouterController nestedRouter;
        public DealershipDAO dealershipDao;

        /**
         * Creates new form AccountView
         */
        public AccountView(AppModel appState, RouterController controller, DealershipDAO dealershipDao) {
                initComponents();
                this.dealershipDao = dealershipDao;
                CardLayout cardLayout = new CardLayout();
                content.setLayout(cardLayout);

                nestedRouter = new AccountRouterController(content, cardLayout);

                nestedRouter.addView(new AccountDetailView(appState, controller, nestedRouter, dealershipDao),
                                AccountRouterController.DETAILS);
                nestedRouter.addView(new AccountHistoryView(appState, controller, nestedRouter, dealershipDao),
                                AccountRouterController.HISTORY);
                nestedRouter.addView(new AccountCurrent(), AccountRouterController.CURRENT);

                historySelectPanel.addMouseListener(new MouseAdapter() {

                        @Override
                        public void mouseClicked(MouseEvent e) {
                                System.out.println("yeahhh details");
                                nestedRouter.goHistory();
                        }

                });
                detailsSelectPanel.addMouseListener(new MouseAdapter() {

                        @Override
                        public void mouseClicked(MouseEvent e) {
                                System.out.println("yeahhh History");
                                nestedRouter.goDetail();
                        }
                });

                currentSelectPanel.addMouseListener(new MouseAdapter() {

                        @Override
                        public void mouseClicked(MouseEvent e) {
                                System.out.println("yeahhh History");
                                nestedRouter.goCurrent();
                        }
                });

        }

        @Override
        public void updatePage() {

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel3 = new javax.swing.JPanel();
                jPanel11 = new javax.swing.JPanel();
                jLabel8 = new javax.swing.JLabel();
                jPanel12 = new javax.swing.JPanel();
                detailsSelectPanel = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                historySelectPanel = new javax.swing.JPanel();
                jLabel51 = new javax.swing.JLabel();
                currentSelectPanel = new javax.swing.JPanel();
                jLabel52 = new javax.swing.JLabel();
                content = new javax.swing.JPanel();

                setBackground(new java.awt.Color(238, 239, 243));
                setPreferredSize(new java.awt.Dimension(1440, 918));

                jPanel3.setBackground(new java.awt.Color(255, 255, 255));
                jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1,
                                new java.awt.Color(204, 204, 204)));

                jPanel11.setBackground(new java.awt.Color(255, 255, 255));
                jPanel11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0,
                                new java.awt.Color(204, 204, 204)));

                jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jLabel8.setForeground(new java.awt.Color(153, 0, 255));
                jLabel8.setText("Account");

                javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
                jPanel11.setLayout(jPanel11Layout);
                jPanel11Layout.setHorizontalGroup(
                                jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel11Layout.createSequentialGroup()
                                                                .addGap(23, 23, 23)
                                                                .addComponent(jLabel8)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel11Layout.setVerticalGroup(
                                jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel11Layout.createSequentialGroup()
                                                                .addGap(26, 26, 26)
                                                                .addComponent(jLabel8)
                                                                .addContainerGap(30, Short.MAX_VALUE)));

                detailsSelectPanel.setBackground(new java.awt.Color(255, 255, 255));
                detailsSelectPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(204, 0, 255));
                jLabel1.setText("Details");

                javax.swing.GroupLayout detailsSelectPanelLayout = new javax.swing.GroupLayout(detailsSelectPanel);
                detailsSelectPanel.setLayout(detailsSelectPanelLayout);
                detailsSelectPanelLayout.setHorizontalGroup(
                                detailsSelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(detailsSelectPanelLayout.createSequentialGroup()
                                                                .addGap(53, 53, 53)
                                                                .addComponent(jLabel1)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                detailsSelectPanelLayout.setVerticalGroup(
                                detailsSelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                detailsSelectPanelLayout.createSequentialGroup()
                                                                                .addContainerGap(14, Short.MAX_VALUE)
                                                                                .addComponent(jLabel1)
                                                                                .addGap(13, 13, 13)));

                historySelectPanel.setBackground(new java.awt.Color(255, 255, 255));
                historySelectPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                jLabel51.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
                jLabel51.setForeground(new java.awt.Color(204, 0, 255));
                jLabel51.setText("History");

                javax.swing.GroupLayout historySelectPanelLayout = new javax.swing.GroupLayout(historySelectPanel);
                historySelectPanel.setLayout(historySelectPanelLayout);
                historySelectPanelLayout.setHorizontalGroup(
                                historySelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(historySelectPanelLayout.createSequentialGroup()
                                                                .addGap(53, 53, 53)
                                                                .addComponent(jLabel51)
                                                                .addContainerGap(245, Short.MAX_VALUE)));
                historySelectPanelLayout.setVerticalGroup(
                                historySelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                historySelectPanelLayout.createSequentialGroup()
                                                                                .addContainerGap(14, Short.MAX_VALUE)
                                                                                .addComponent(jLabel51)
                                                                                .addGap(13, 13, 13)));

                currentSelectPanel.setBackground(new java.awt.Color(255, 255, 255));
                currentSelectPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                jLabel52.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
                jLabel52.setForeground(new java.awt.Color(204, 0, 255));
                jLabel52.setText("Current Rentals");

                javax.swing.GroupLayout currentSelectPanelLayout = new javax.swing.GroupLayout(currentSelectPanel);
                currentSelectPanel.setLayout(currentSelectPanelLayout);
                currentSelectPanelLayout.setHorizontalGroup(
                                currentSelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(currentSelectPanelLayout.createSequentialGroup()
                                                                .addGap(53, 53, 53)
                                                                .addComponent(jLabel52)
                                                                .addContainerGap(153, Short.MAX_VALUE)));
                currentSelectPanelLayout.setVerticalGroup(
                                currentSelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                currentSelectPanelLayout.createSequentialGroup()
                                                                                .addContainerGap(14, Short.MAX_VALUE)
                                                                                .addComponent(jLabel52)
                                                                                .addGap(13, 13, 13)));

                javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
                jPanel12.setLayout(jPanel12Layout);
                jPanel12Layout.setHorizontalGroup(
                                jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel12Layout.createSequentialGroup()
                                                                .addGroup(jPanel12Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(jPanel12Layout
                                                                                                .createSequentialGroup()
                                                                                                .addContainerGap(
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(currentSelectPanel,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel12Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(21, 21, 21)
                                                                                                .addGroup(jPanel12Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(detailsSelectPanel,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addGroup(jPanel12Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                                                                .addComponent(historySelectPanel,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                                .addContainerGap(23, Short.MAX_VALUE)));
                jPanel12Layout.setVerticalGroup(
                                jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel12Layout.createSequentialGroup()
                                                                .addGap(42, 42, 42)
                                                                .addComponent(detailsSelectPanel,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(historySelectPanel,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(currentSelectPanel,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(574, Short.MAX_VALUE)));

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addComponent(jPanel11,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, 0)
                                                                .addComponent(jPanel12,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGap(0, 0, 0)));

                javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
                content.setLayout(contentLayout);
                contentLayout.setHorizontalGroup(
                                contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 1019, Short.MAX_VALUE));
                contentLayout.setVerticalGroup(
                                contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 0, Short.MAX_VALUE));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jPanel3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, 0)
                                                                .addComponent(content,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGap(0, 0, 0)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        }// </editor-fold>//GEN-END:initComponents

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel content;
        private javax.swing.JPanel currentSelectPanel;
        private javax.swing.JPanel detailsSelectPanel;
        private javax.swing.JPanel historySelectPanel;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel51;
        private javax.swing.JLabel jLabel52;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JPanel jPanel11;
        private javax.swing.JPanel jPanel12;
        private javax.swing.JPanel jPanel3;
        // End of variables declaration//GEN-END:variables
}
